<a href="https://colab.research.google.com/github/jittakorn-ch/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np     ### package สำหรับทำงานกับ ข้อมูลที่เป็นตัวเลข อยู่ในรูปแบบ matrix

# Numpy Array

## สร้าง numpy array (matrix)

In [5]:
np_a = np.array([[1,2,3],[4,5,6]])    ### สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [7]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np_a.shape

(2, 3)

In [10]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

### matrix transpose

In [11]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### สร้าง matrix เริ่มต้น (zeros,ones)

In [12]:
# matrix zeros
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# matrix ones
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
# สร้าง matrix ที่มีค่าเป็น 200
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

### สร้าง matrix random

In [15]:
np.random.randn(5,5)  ### random เลขมาจาก normal distribution ที่มี mu=0, dtd=1

array([[ 0.08825958, -0.1491198 , -0.02933621,  0.8323579 ,  0.84765414],
       [-2.20778143,  0.67957533,  0.07877295,  3.04606021, -0.58439283],
       [-1.71101787,  0.59932767, -0.5140253 , -1.68825669,  0.44126907],
       [ 0.02075554, -0.64271496, -0.5685522 , -0.35041063,  2.06393515],
       [ 0.6511343 , -0.91496635,  1.6232063 ,  0.46230595,  0.96051406]])

In [16]:
2+(5*np.random.randn(3,3))  ### random เลขมาจาก normal distribution ที่มี mu=2, dtd=5

array([[-1.91345086,  2.6456149 , -0.93398007],
       [ 1.79719087, -0.19624575, -0.16342999],
       [ 3.73082813, -8.87685192,  4.048866  ]])

In [18]:
np.random.randint(5,11,(4,5))  ### random เลขจำนวนเต็ม ระหว่าง [5,11) ขนาด (4x5)

array([[ 7, 10,  7,  6,  6],
       [ 8,  8,  6,  6,  7],
       [ 5,  6,  7, 10,  9],
       [10,  7,  7,  6,  9]])